const playersData = [
  // 공격수
  {
    player_name: 'Erling Haaland',
    speed: 89,
    goal_decision: 87,
    shoot_power: 88,
    defence: 48,
    stamina: 91,
  },
  {
    player_name: 'Mohamed Salah',
    speed: 93,
    goal_decision: 89,
    shoot_power: 87,
    defence: 45,
    stamina: 90,
  },
  {
    player_name: 'Antoine Griezmann',
    speed: 88,
    goal_decision: 85,
    shoot_power: 86,
    defence: 50,
    stamina: 88,
  },
  {
    player_name: 'Sadio Mane',
    speed: 95,
    goal_decision: 86,
    shoot_power: 88,
    defence: 42,
    stamina: 89,
  },
  {
    player_name: 'Roberto Firmino',
    speed: 82,
    goal_decision: 84,
    shoot_power: 85,
    defence: 55,
    stamina: 87,
  },
  {
    player_name: 'Karim Benzema',
    speed: 85,
    goal_decision: 88,
    shoot_power: 87,
    defence: 50,
    stamina: 86,
  },
  {
    player_name: 'Marcus Rashford',
    speed: 93,
    goal_decision: 83,
    shoot_power: 86,
    defence: 47,
    stamina: 88,
  },
  {
    player_name: 'Raheem Sterling',
    speed: 94,
    goal_decision: 85,
    shoot_power: 83,
    defence: 40,
    stamina: 91,
  },
  {
    player_name: 'Timo Werner',
    speed: 94,
    goal_decision: 86,
    shoot_power: 85,
    defence: 45,
    stamina: 90,
  },
  {
    player_name: 'Son Heung-Min',
    speed: 90,
    goal_decision: 84,
    shoot_power: 85,
    defence: 52,
    stamina: 87,
  },
  // 수비수
  {
    player_name: 'Aymeric Laporte',
    speed: 74,
    goal_decision: 58,
    shoot_power: 70,
    defence: 87,
    stamina: 85,
  },
  {
    player_name: 'Trent Alexander-Arnold',
    speed: 85,
    goal_decision: 70,
    shoot_power: 75,
    defence: 75,
    stamina: 88,
  },
  {
    player_name: 'Giorgio Chiellini',
    speed: 70,
    goal_decision: 40,
    shoot_power: 50,
    defence: 95,
    stamina: 80,
  },
  {
    player_name: 'David Alaba',
    speed: 78,
    goal_decision: 70,
    shoot_power: 75,
    defence: 83,
    stamina: 87,
  },
  {
    player_name: 'Thiago Silva',
    speed: 70,
    goal_decision: 50,
    shoot_power: 55,
    defence: 89,
    stamina: 82,
  },
  {
    player_name: 'Leonardo Bonucci',
    speed: 72,
    goal_decision: 45,
    shoot_power: 50,
    defence: 90,
    stamina: 83,
  },
  {
    player_name: 'Diego Carlos',
    speed: 78,
    goal_decision: 40,
    shoot_power: 45,
    defence: 87,
    stamina: 85,
  },
  {
    player_name: 'Mats Hummels',
    speed: 68,
    goal_decision: 50,
    shoot_power: 55,
    defence: 89,
    stamina: 80,
  },
  {
    player_name: 'Marquinhos',
    speed: 76,
    goal_decision: 65,
    shoot_power: 68,
    defence: 89,
    stamina: 84,
  },
  {
    player_name: 'Milan Skriniar',
    speed: 74,
    goal_decision: 55,
    shoot_power: 60,
    defence: 90,
    stamina: 82,
  },
  // 미드필더
  {
    player_name: 'Marco Reus',
    speed: 85,
    goal_decision: 87,
    shoot_power: 85,
    defence: 55,
    stamina: 86,
  },
  {
    player_name: 'Christian Eriksen',
    speed: 77,
    goal_decision: 88,
    shoot_power: 84,
    defence: 55,
    stamina: 85,
  },
  {
    player_name: 'Sergej Milinkovic-Savic',
    speed: 81,
    goal_decision: 85,
    shoot_power: 83,
    defence: 75,
    stamina: 87,
  },
  {
    player_name: 'Thomas Muller',
    speed: 77,
    goal_decision: 89,
    shoot_power: 85,
    defence: 60,
    stamina: 88,
  },
  {
    player_name: 'Jorginho',
    speed: 70,
    goal_decision: 88,
    shoot_power: 80,
    defence: 75,
    stamina: 89,
  },
  {
    player_name: 'Saul Niguez',
    speed: 82,
    goal_decision: 85,
    shoot_power: 82,
    defence: 75,
    stamina: 87,
  },
  {
    player_name: 'Thiago Alcantara',
    speed: 79,
    goal_decision: 87,
    shoot_power: 82,
    defence: 70,
    stamina: 88,
  },
  {
    player_name: 'Fabinho',
    speed: 78,
    goal_decision: 80,
    shoot_power: 80,
    defence: 82,
    stamina: 88,
  },
  {
    player_name: 'Rodri',
    speed: 75,
    goal_decision: 80,
    shoot_power: 78,
    defence: 85,
    stamina: 87,
  },
  {
    player_name: 'Kante',
    speed: 85,
    goal_decision: 78,
    shoot_power: 75,
    defence: 90,
    stamina: 90,
  },
];

export default playersData;
