const playersData = [
    // 공격수
    {    
      playerName: 'Erling Haaland',   
      speed: 89,
      goalDecision: 87,
      shootPower: 88,
      defence: 48,
      stamina: 91,
    },
    {    
      playerName: 'Mohamed Salah',     
      speed: 93,
      goalDecision: 89,
      shootPower: 87,
      defence: 45,
      stamina: 90,
    },
    {    
      playerName: 'Antoine Griezmann',  
      speed: 88,
      goalDecision: 85,
      shootPower: 86,
      defence: 50,
      stamina: 88,
    },
    {    
      playerName: 'Sadio Mane',
      speed: 95,
      goalDecision: 86,
      shootPower: 88,
      defence: 42,
      stamina: 89,
    },
    {    
      playerName: 'Roberto Firmino',
      speed: 82,
      goalDecision: 84,
      shootPower: 85,
      defence: 55,
      stamina: 87,
    },
    {    
      playerName: 'Karim Benzema',
      speed: 85,
      goalDecision: 88,
      shootPower: 87,
      defence: 50,
      stamina: 86,
    },
    {    
      playerName: 'Marcus Rashford',
      speed: 93,
      goalDecision: 83,
      shootPower: 86,
      defence: 47,
      stamina: 88,
    },
    {    
      playerName: 'Raheem Sterling',
      speed: 94,
      goalDecision: 85,
      shootPower: 83,
      defence: 40,
      stamina: 91,
    },
    {    
      playerName: 'Timo Werner',
      speed: 94,
      goalDecision: 86,
      shootPower: 85,
      defence: 45,
      stamina: 90,
    },
    {    
      playerName: 'Son Heung-Min',
      speed: 90,
      goalDecision: 84,
      shootPower: 85,
      defence: 52,
      stamina: 87,
    },
    // 수비수
    {    
      playerName: 'Aymeric Laporte',
      speed: 74,
      goalDecision: 58,
      shootPower: 70,
      defence: 87,
      stamina: 85,
    },
    {    
      playerName: 'Trent Alexander-Arnold',
      speed: 85,
      goalDecision: 70,
      shootPower: 75,
      defence: 75,
      stamina: 88,
    },
    {    
      playerName: 'Giorgio Chiellini',
      speed: 70,
      goalDecision: 40,
      shootPower: 50,
      defence: 95,
      stamina: 80,
    },
    {    
      playerName: 'David Alaba',
      speed: 78,
      goalDecision: 70,
      shootPower: 75,
      defence: 83,
      stamina: 87,
    },
    {    
      playerName: 'Thiago Silva',
      speed: 70,
      goalDecision: 50,
      shootPower: 55,
      defence: 89,
      stamina: 82,
    },
    {    
      playerName: 'Leonardo Bonucci',
      speed: 72,
      goalDecision: 45,
      shootPower: 50,
      defence: 90,
      stamina: 83,
    },
    {    
      playerName: 'Diego Carlos',
      speed: 78,
      goalDecision: 40,
      shootPower: 45,
      defence: 87,
      stamina: 85,
    },
    {    
      playerName: 'Mats Hummels',
      speed: 68,
      goalDecision: 50,
      shootPower: 55,
      defence: 89,
      stamina: 80,
    },
    {    
      playerName: 'Marquinhos',
      speed: 76,
      goalDecision: 65,
      shootPower: 68,
      defence: 89,
      stamina: 84,
    },
    {    
      playerName: 'Milan Skriniar',
      speed: 74,
      goalDecision: 55,
      shootPower: 60,
      defence: 90,
      stamina: 82,
    },
    // 미드필더
    {    
      playerName: 'Marco Reus',
      speed: 85,
      goalDecision: 87,
      shootPower: 85,
      defence: 55,
      stamina: 86,
    },
    {    
      playerName: 'Christian Eriksen',
      speed: 77,
      goalDecision: 88,
      shootPower: 84,
      defence: 55,
      stamina: 85,
    },
    {    
      playerName: 'Sergej Milinkovic-Savic',
      speed: 81,
      goalDecision: 85,
      shootPower: 83,
      defence: 75,
      stamina: 87,
    },
    {    
      playerName: 'Thomas Muller',
      speed: 77,
      goalDecision: 89,
      shootPower: 85,
      defence: 60,
      stamina: 88,
    },
    {    
      playerName: 'Jorginho',
      speed: 70,
      goalDecision: 88,
      shootPower: 80,
      defence: 75,
      stamina: 89,
    },
    {    
      playerName: 'Saul Niguez',
      speed: 82,
      goalDecision: 85,
      shootPower: 82,
      defence: 75,
      stamina: 87,
    },
    {    
      playerName: 'Thiago Alcantara',
      speed: 79,
      goalDecision: 87,
      shootPower: 82,
      defence: 70,
      stamina: 88,
    },
    {    
      playerName: 'Fabinho',
      speed: 78,
      goalDecision: 80,
      shootPower: 80,
      defence: 82,
      stamina: 88,
    },
    {    
      playerName: 'Rodri',
      speed: 75,
      goalDecision: 80,
      shootPower: 78,
      defence: 85,
      stamina: 87,
    },
    {    
      playerName: 'Kante',
      speed: 85,
      goalDecision: 78,
      shootPower: 75,
      defence: 90,
      stamina: 90,
    },
  ];

  export default playersData;
  